
package ch.fhnw.bank.client.soap.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPBankService", targetNamespace = "http://soap.server.bank.fhnw.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPBankService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.CreateAccountResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/createAccountRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/createAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/createAccount/Fault/IOException")
    })
    public String createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeAccount", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.CloseAccount")
    @ResponseWrapper(localName = "closeAccountResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.CloseAccountResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/closeAccountRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/closeAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/closeAccount/Fault/IOException")
    })
    public boolean closeAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.DepositResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/depositRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/depositResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/deposit/Fault/IOException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/deposit/Fault/InactiveException")
    })
    public void deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws OverdrawException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.WithdrawResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/withdrawRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/withdrawResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/withdraw/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/withdraw/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/withdraw/Fault/InactiveException")
    })
    public void withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountNumbersResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountNumbersRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountNumbersResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountNumbers/Fault/IOException")
    })
    public List<String> getAccountNumbers()
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalance", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountBalance")
    @ResponseWrapper(localName = "getAccountBalanceResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountBalanceResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountBalanceRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountBalanceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountBalance/Fault/IOException")
    })
    public double getAccountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountOwner", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountOwner")
    @ResponseWrapper(localName = "getAccountOwnerResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.GetAccountOwnerResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountOwnerRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountOwnerResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/getAccountOwner/Fault/IOException")
    })
    public String getAccountOwner(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAccountActive", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.IsAccountActive")
    @ResponseWrapper(localName = "isAccountActiveResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.IsAccountActiveResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/isAccountActiveRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/isAccountActiveResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/isAccountActive/Fault/IOException")
    })
    public boolean isAccountActive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws OverdrawException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://soap.server.bank.fhnw.ch/", className = "ch.fhnw.bank.client.soap.jaxws.TransferResponse")
    @Action(input = "http://soap.server.bank.fhnw.ch/SOAPBankService/transferRequest", output = "http://soap.server.bank.fhnw.ch/SOAPBankService/transferResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/transfer/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/transfer/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.server.bank.fhnw.ch/SOAPBankService/transfer/Fault/InactiveException")
    })
    public void transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

}
